### ISSUE TITLE
Выкидывает с сервера

### ISSUE THREAD

**Issue by Geo3gamer** [KarbonPowered/Karbon#11]
Если в чат написать кавычку `"`, то может выкинуть весь сервер сразу (так происходит у меня) или того, кто написал сообщение
![](https://media.discordapp.net/attachments/730349425075028018/829031004655583332/2021-04-06_19.32.47.png)

**Comment by neroslava** [comment]
кривая генерация пакета, судя по всему кривой json пакета chat

**Comment by andreypfau** [comment]
Это связанно что символы для json не экранируются, я это уже вроде исправлял. Нужно будет проверить

**Comment by andreypfau** [comment]
fixed
