### ISSUE TITLE
Идея новые команды консоли

### ISSUE THREAD

**Issue by White-145** [KarbonPowered/Karbon#12]
### Чего я хочу:
Новые команды поверх ванильных по типу встроеного WE и /do (/do <selector> <action id (например karbonpowered:jump (jump (для всех) selebrate (для жителей и нежителей) eat (есть траву, для лошадей овец еще там кто может)))>)

**Comment by andreypfau** [comment]
Напиши об этом в https://github.com/KarbonPowered/Karbon/discussions
